In [1]:
import torch

In [2]:
x = torch.Tensor(5,3)
print(x)


 0.0000e+00  0.0000e+00  1.3464e-23
 4.5780e-41  1.3465e-23  4.5780e-41
 1.0232e-19  4.5780e-41  1.0232e-19
 4.5780e-41  1.2675e-19  4.5780e-41
 1.2209e-19  4.5780e-41 -8.9945e+10
[torch.FloatTensor of size 5x3]



In [7]:
print(x.size(1))

3


In [4]:
x= torch.rand(5,3)

In [5]:
print(x)


 0.3430  0.8862  0.3262
 0.6808  0.1929  0.2802
 0.8464  0.7169  0.2457
 0.5896  0.6916  0.9559
 0.5947  0.2062  0.1809
[torch.FloatTensor of size 5x3]



In [8]:
V_data = [1.,2.,3.]
V= torch.Tensor(V_data)
print(V)

M_data = [[1.,2.,3.],[4.,5.,6]]
M = torch.Tensor(M_data)
print(M)


 1
 2
 3
[torch.FloatTensor of size 3]


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]



In [12]:
x = torch.rand(5,3)
y= torch.rand(5,3)
result=x+y
torch.add(x,y,out=result)
print(result)


 1.6334  1.3289  1.3198
 1.7506  1.1809  1.4096
 1.4959  0.9584  1.9472
 0.6665  1.0896  0.5773
 1.0401  0.3212  0.4207
[torch.FloatTensor of size 5x3]



In [14]:
print(x[:,0])


 0.9292
 0.8348
 0.7149
 0.0766
 0.7425
[torch.FloatTensor of size 5]



In [15]:
T_data = [ [[1.,2.] ,[3.,4.]] , [[5.,6.] ,[7.,8.]] ]

In [16]:
T = torch.Tensor(T_data)

In [17]:
print(T)


(0 ,.,.) = 
  1  2
  3  4

(1 ,.,.) = 
  5  6
  7  8
[torch.FloatTensor of size 2x2x2]



In [18]:
print(T[:,-1,:])


 3  4
 7  8
[torch.FloatTensor of size 2x2]



In [19]:
x_1=torch.randn(2,5)
y_1 = torch.randn(3,5)
z_1 = torch.cat([x_1,y_1])
print(z_1)


-0.8135 -0.9635 -1.3708 -0.5016 -0.0324
-0.1461 -1.5469  1.4407 -1.2093  0.4512
-0.7313 -1.1250  1.4204  1.0399  1.0966
 1.4053 -0.7432  2.0635 -1.2703  0.6321
 0.8792  0.8287 -1.9745 -0.1265  0.9368
[torch.FloatTensor of size 5x5]



In [21]:
x_2 = torch.randn(2,3)
y_2 = torch.randn(2,5)

In [23]:
z_2= torch.cat([x_2,y_2],1)
print(z_2)


 2.1073  0.2548  1.0367 -0.8923 -1.1505 -1.8006  0.1211  1.9486
-0.7659  0.3230 -0.2931 -2.0191  1.0723 -0.5371 -0.4692 -0.0167
[torch.FloatTensor of size 2x8]



In [25]:
x= torch.randn(2,3,4)
y=x.view(2,-1)
print(y)



Columns 0 to 9 
-0.5561 -1.4659 -1.0729  0.2011  0.1106 -0.1440 -0.3654  2.6997  0.8910 -0.0824
-0.9755 -0.6624  1.5639  1.1035  0.6300 -0.2899 -1.0589  0.0587 -0.7938 -0.3761

Columns 10 to 11 
-0.2390 -0.2094
-1.9184 -0.8365
[torch.FloatTensor of size 2x12]



In [28]:
a= torch.ones(5,5)

In [29]:
print(a)


 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
[torch.FloatTensor of size 5x5]



In [33]:
b=a.numpy()
print(b)


[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(1,1,out=a)
print(a)

[ 2.  2.  2.  2.  2.]


In [35]:
torch.cuda.is_available()

True

In [36]:
x = x.cuda()

In [37]:
print(x)


(0 ,.,.) = 
 -0.5561 -1.4659 -1.0729  0.2011
  0.1106 -0.1440 -0.3654  2.6997
  0.8910 -0.0824 -0.2390 -0.2094

(1 ,.,.) = 
 -0.9755 -0.6624  1.5639  1.1035
  0.6300 -0.2899 -1.0589  0.0587
 -0.7938 -0.3761 -1.9184 -0.8365
[torch.cuda.FloatTensor of size 2x3x4 (GPU 0)]



In [38]:
y= y.cuda()
print(y)



Columns 0 to 9 
-0.5561 -1.4659 -1.0729  0.2011  0.1106 -0.1440 -0.3654  2.6997  0.8910 -0.0824
-0.9755 -0.6624  1.5639  1.1035  0.6300 -0.2899 -1.0589  0.0587 -0.7938 -0.3761

Columns 10 to 11 
-0.2390 -0.2094
-1.9184 -0.8365
[torch.cuda.FloatTensor of size 2x12 (GPU 0)]



In [39]:
print(x+y)


(0 ,.,.) = 
 -1.1123 -2.9318 -2.1459  0.4021
  0.2212 -0.2879 -0.7308  5.3994
  1.7820 -0.1648 -0.4779 -0.4187

(1 ,.,.) = 
 -1.9511 -1.3247  3.1279  2.2070
  1.2600 -0.5799 -2.1179  0.1174
 -1.5876 -0.7523 -3.8367 -1.6730
[torch.cuda.FloatTensor of size 2x3x4 (GPU 0)]



/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/tensor.py:293: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)


In [40]:
dtype = torch.cuda.FloatTensor

In [41]:
x = torch.randn(5,3).type(dtype)

In [42]:
print(x)


 0.5055  0.7177  0.2426
 0.9618 -2.0182 -0.4553
-0.0749 -2.5753  1.3525
-0.9647  0.2432  2.3254
 0.4493  0.2374 -0.7440
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]



In [44]:
use_cuda = torch.cuda.is_available()
dypte = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor

In [45]:
x = torch.FloatTensor(8,1,6,1)
y= torch.FloatTensor(7,1,5)

In [47]:
print(x+y)


(0 ,0 ,.,.) = 
  5.1229e-20  2.5615e-20  5.1229e-20  2.5615e-20  2.5615e-20
  2.5614e-20  9.1561e-41  2.5614e-20  9.1561e-41  4.5780e-41
  5.1229e-20  2.5615e-20  5.1229e-20  2.5615e-20  2.5615e-20
  2.5614e-20  9.1561e-41  2.5614e-20  9.1561e-41  4.5780e-41
  1.0038e-19  7.4766e-20  1.0038e-19  7.4766e-20  7.4766e-20
  2.5614e-20  9.1561e-41  2.5614e-20  9.1561e-41  4.5780e-41

(0 ,1 ,.,.) = 
  2.5615e-20  2.5615e-20  2.5615e-20  2.5615e-20  2.5615e-20
  4.5780e-41  4.5780e-41  4.5780e-41  4.5780e-41  4.5780e-41
  2.5615e-20  2.5615e-20  2.5615e-20  2.5615e-20  2.5615e-20
  4.5780e-41  4.5780e-41  4.5780e-41  4.5780e-41  4.5780e-41
  7.4766e-20  7.4766e-20  7.4766e-20  7.4766e-20  7.4766e-20
  4.5780e-41  4.5780e-41  4.5780e-41  4.5780e-41  4.5780e-41

(0 ,2 ,.,.) = 
  2.5615e-20  2.5615e-20  5.1229e-20  2.5615e-20  5.1229e-20
  4.5939e-41  4.5780e-41  2.5614e-20  9.1561e-41  2.5614e-20
  2.5615e-20  2.5615e-20  5.1229e-20  2.5615e-20  5.1229e-20
  4.5939e-41  4.5780e-41  2.5614e-20 

In [48]:
x= torch.ones(4)

In [49]:
xx=x.view(4,-1)
y= torch.ones(5)
print(xx+y)


 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2
[torch.FloatTensor of size 4x5]



In [50]:
x = torch.Tensor([0.0,10.0,20.0,30.0])
y= torch.Tensor([1.0,2.0,3.0])
x.view(4,-1)+y


  1   2   3
 11  12  13
 21  22  23
 31  32  33
[torch.FloatTensor of size 4x3]